### ISSUE TITLE
[TODO] 環境構築

### ISSUE THREAD

**Issue by sueCalystegia00** [YoslabEngineers/seminar-report-editor#4]
# 概要

開発環境をDockerで構築する

# 目的

まずはここから

# 提案内容

森川くんがメインで作業のモブプロ

# タスク

- [x] Next.js
- [x] DB(MySQL)
- [ ] phpMyAdmin

**Comment by tagahei** [comment]
MySQLClientについては，Docker内ではなくそれぞれ使いましょう
Mac用：[Sequel](https://apps.apple.com/us/app/sequel-ace/id1518036000)
Windows？：[HeidiSQL](https://www.heidisql.com/)

**Comment by sueCalystegia00** [comment]
@tkming0916 にも共有したのでDone
